# Generated by Django 4.2.4 on 2023-08-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_alter_items_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'Items'},
        ),
    ]
