# Generated by Django 4.2.4 on 2023-08-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_alter_items_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('display_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
