# Generated by Django 4.2.4 on 2023-08-28 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='display_name',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^(?=.*\\d)(?=.*[A-Z])(?=.*[&^%$#@!~`<>?/:;}{][)+()]}].,_=)', message='Password must contain atleast one uppercase letter, one digit and one special character')]),
        ),
    ]
