# Generated by Django 4.2.4 on 2023-08-29 10:41

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Items', '0007_alter_customer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField(default=datetime.datetime(2023, 8, 29, 15, 41, 12, 717227))),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Items.items')),
            ],
        ),
    ]
