# Generated by Django 4.2.4 on 2023-08-29 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 29, 10, 42, 47, 528438, tzinfo=datetime.timezone.utc)),
        ),
    ]
