# Generated by Django 4.2.4 on 2023-08-29 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 8, 29, 10, 43, 13, 550067, tzinfo=datetime.timezone.utc)),
        ),
    ]
